### ISSUE TITLE
iOS Wallet Bug Tracker

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#47]
## zECC Wallet V5
- [ ] pressing skip on the "create new wallet" flow crashes the app
- [ ] Toggle between "scan address" to "your address" doesn't work
- [ ] Sizing and spacing on iPhone 8 is all over over the place. I'm sure this is just tweaking, but every screen has spill over.
