### ISSUE TITLE
Full Memo and outbound transaction restore support

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#79]
As a user I would like to be able to receive memos sent to me and be able to restore my wallet to view all memo information incoming and outgoing.

Requirements:
- [x] Demo app is updated to restore memos
- [x] Demo app shows outgoing transactions
- [ ] Incoming memos are available and can be shown to the user in the zECC app
- [ ] On wallet restore, outgoing memos are added to transactions in the zECC app
- [ ] Outgoing transactions are restored into the wallet in the zECC app
