### ISSUE TITLE
revise tx detail screen

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#84]
As a user, I would like to be able to see the details of my transactions to accurately display

- [ ] The amount I sent or received
- [ ] Who I sent them to
- [ ] When I sent or receive funds
- [ ] The memo associated with the transaction
- [ ] The status of transaction confirmation including confirmation blocks
- [ ] The status of change associated with a sent transaction
- [ ] the amount of change I can expect
- [ ] Implemented with the provided designs

@geffenz Please comment the finalized designs in a thread here when they are complete.

**Comment by geffenz** [comment]
![image.png](https://images.zenhubusercontent.com/5ddc49a1bc69ec000196b9a0/6d0159cf-bd96-4c80-b42d-ea910772e8d1)
