### ISSUE TITLE
iOS Application Logs

### ISSUE THREAD

**Issue by braddmiller** [zcash/zcash-ios-wallet#94]
Implement extensive logging in the iOS app to aid in development and bug discovery.

Requirements:
- [x] All asserts/failures/crashes are logged
- [x] All user actions are logged
- [ ] All interactions with librustzcash are logged
- [x] Logs do not expose information about seeds or keys
- [x] Logs are viewable by the user (through any means, including copy/paste to external app)
